[package]
name = "dziwak-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }
thiserror = "2.0"
lz4_flex = { version = "0.11", default-features = false, features = ["std", "safe-encode", "safe-decode"] }
ab_glyph = { version = "0.2", default-features = false, features = ["std"] }
